export const architects = [
  {
    id: 1, name: "Roshan Perera", role: "Architect", category: "Architecture",
    rating: 4.9, reviewCount: 34,
    company: "Perera & Associates",
    location: "Colombo 03, Sri Lanka",
    available: "10th Feb",
    hours: "9AM – 6PM",
    about: "Roshan is a leading architect based in Colombo with over 12 years of experience in residential, commercial, and hospitality projects across Sri Lanka. Inspired by Geoffrey Bawa's tropical modernism, he creates spaces that breathe with the island's climate and landscape.",
    specializations: ["Tropical Modernism", "Residential Design", "Hospitality & Resorts", "Sustainable Construction"],
    experience: [
      { company: "Perera & Associates", role: "Principal Architect", type: "Full-time", period: "Jan 2016 – Present", description: "Leads a Colombo-based practice delivering award-winning residential and resort projects across Sri Lanka." },
      { company: "Bawa Architecture Studio", role: "Senior Architect", type: "Full-time", period: "Mar 2011 – Dec 2015", description: "Worked on high-profile hospitality and private residence projects in Galle and Bentota." },
    ],
    education: [{ school: "University of Moratuwa", dept: "Bachelor of Science in Architecture", period: "2004 – 2009" }],
    reviews: [
      { name: "Chaminda Jayawardena", rating: 5, text: "Roshan understood exactly what we wanted — a home that feels open, breezy, and rooted in Sri Lanka. Exceptional work." },
      { name: "Nilufar Hameed", rating: 5, text: "His knowledge of tropical design is unmatched. Our villa in Weligama is everything we dreamed of." },
    ],
    portfolio: [
      { url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop", caption: "Weligama Bay Villa", category: "Residential" },
      { url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop", caption: "Tropical Resort, Bentota", category: "Hospitality" },
      { url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=600&fit=crop", caption: "Private Residence, Colombo 07", category: "Residential" },
      { url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop", caption: "Coastal House, Galle", category: "Residential" },
    ],
  },
  {
    id: 2, name: "Dilani Wijesinghe", role: "Interior Designer", category: "Interior Design",
    rating: 4.7, reviewCount: 21,
    company: "Studio Dilani",
    location: "Colombo 07, Sri Lanka",
    available: "12th Feb",
    hours: "10AM – 7PM",
    about: "Dilani brings a sophisticated blend of Sri Lankan artisan tradition and contemporary design to every interior. Her work celebrates local craftsmanship — lacquerwork, brass, handloom textiles — woven into modern, liveable spaces.",
    specializations: ["Luxury Residential", "Boutique Hospitality", "Local Craft Integration", "Space Planning"],
    experience: [
      { company: "Studio Dilani", role: "Creative Director", type: "Full-time", period: "Aug 2019 – Present", description: "Runs a boutique interior design studio in Colombo 7, known for blending contemporary aesthetics with Sri Lankan craft." },
      { company: "Hiran Cooray Design Group", role: "Senior Designer", type: "Full-time", period: "Feb 2014 – Jul 2019", description: "Led interior design for several boutique hotels and private residences across Colombo and the South Coast." },
    ],
    education: [{ school: "SLIIT", dept: "Interior Design", period: "2009 – 2013" }],
    reviews: [
      { name: "Sanjaya Mendis", rating: 5, text: "Dilani transformed our apartment in Colombo 7 into something truly special. She understood our taste immediately." },
      { name: "Preethi Fernando", rating: 4, text: "Beautiful work. She sourced local materials we never would have found ourselves. Very pleased with the result." },
    ],
    portfolio: [
      { url: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&h=600&fit=crop", caption: "Living Room, Colombo 07", category: "Residential" },
      { url: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&h=600&fit=crop", caption: "Boutique Suite, South Coast", category: "Hospitality" },
      { url: "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=800&h=600&fit=crop", caption: "Master Bedroom, Cinnamon Gardens", category: "Residential" },
      { url: "https://images.unsplash.com/photo-1616137466211-f939a420be84?w=800&h=600&fit=crop", caption: "Open Kitchen, Colombo", category: "Residential" },
    ],
  },
  {
    id: 3, name: "Kavinda Rajapaksa", role: "Landscape Architect", category: "Landscape Architecture",
    rating: 4.5, reviewCount: 16,
    company: "Greenlane Lanka",
    location: "Kandy, Sri Lanka",
    available: "14th Feb",
    hours: "8AM – 5PM",
    about: "Kavinda specialises in tropical landscape architecture, creating gardens and outdoor environments that thrive in Sri Lanka's climate. His projects range from private tea estate gardens to resort grounds and urban green spaces.",
    specializations: ["Tropical Garden Design", "Resort Landscaping", "Water Features", "Sustainable Planting"],
    experience: [
      { company: "Greenlane Lanka", role: "Principal Landscape Architect", type: "Full-time", period: "Apr 2018 – Present", description: "Delivers residential and resort landscape projects across the Hill Country and South Coast." },
      { company: "Scape Studio", role: "Landscape Architect", type: "Full-time", period: "Jun 2012 – Mar 2018", description: "Contributed to large-scale resort and hotel grounds projects in Galle, Bentota, and Sigiriya." },
    ],
    education: [{ school: "University of Peradeniya", dept: "Agriculture & Landscape Design", period: "2007 – 2011" }],
    reviews: [
      { name: "Tharanga Wickramasinghe", rating: 5, text: "Our tea estate garden is now the highlight of every guest visit. Kavinda has an extraordinary eye for tropical planting." },
      { name: "Suresh Bandara", rating: 4, text: "Very professional and full of great ideas. The resort grounds look stunning." },
    ],
    portfolio: [
      { url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop", caption: "Tea Estate Garden, Nuwara Eliya", category: "Estate" },
      { url: "https://images.unsplash.com/photo-1503756234508-e54369723f13?w=800&h=600&fit=crop", caption: "Resort Infinity Pool, Bentota", category: "Hospitality" },
      { url: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=600&fit=crop", caption: "Tropical Garden, Kandy", category: "Residential" },
      { url: "https://images.unsplash.com/photo-1540541338537-71acf6f14e1a?w=800&h=600&fit=crop", caption: "Hotel Grounds, Sigiriya", category: "Hospitality" },
    ],
  },
  {
    id: 4, name: "Amali Senanayake", role: "Interior Designer", category: "Interior Design",
    rating: 4.4, reviewCount: 13,
    company: "Amali Design Co.",
    location: "Galle, Sri Lanka",
    available: "15th Feb",
    hours: "9AM – 5PM",
    about: "Amali is based in Galle and specialises in heritage renovation and colonial-style interiors. She has a deep appreciation for the Dutch colonial architecture of the Galle Fort area and brings that sensitivity to residential and boutique hotel projects.",
    specializations: ["Heritage Renovation", "Colonial Interiors", "Boutique Hotels", "Material Sourcing"],
    experience: [
      { company: "Amali Design Co.", role: "Founder & Lead Designer", type: "Full-time", period: "Mar 2020 – Present", description: "Runs an independent studio focused on heritage home renovations and boutique hotel interiors in the South." },
      { company: "Galle Heritage Trust", role: "Design Consultant", type: "Contract", period: "Jan 2016 – Feb 2020", description: "Provided interior design consultancy for heritage property restorations within the Galle Fort UNESCO zone." },
    ],
    education: [{ school: "University of Moratuwa", dept: "Architecture", period: "2010 – 2015" }],
    reviews: [
      { name: "Hannah Webb", rating: 5, text: "Amali restored our Galle Fort villa with incredible care and taste. Every detail is perfect." },
      { name: "Kasun Ranatunga", rating: 4, text: "Deeply knowledgeable about heritage properties. Our home feels authentic and beautiful." },
    ],
    portfolio: [
      { url: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&h=600&fit=crop", caption: "Heritage Villa, Galle Fort", category: "Heritage" },
      { url: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&h=600&fit=crop", caption: "Colonial Suite, Boutique Hotel", category: "Hospitality" },
      { url: "https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800&h=600&fit=crop", caption: "Dutch Colonial Bedroom", category: "Heritage" },
      { url: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&h=600&fit=crop", caption: "Restored Living Room, Galle", category: "Residential" },
    ],
  },
  {
    id: 5, name: "Nishantha Gunasekara", role: "Architect", category: "Architecture",
    rating: 4.8, reviewCount: 27,
    company: "Gunasekara Architects",
    location: "Negombo, Sri Lanka",
    available: "16th Feb",
    hours: "9AM – 6PM",
    about: "Nishantha brings 15 years of experience in coastal residential and commercial design. He specialises in buildings that maximise natural ventilation and integrate seamlessly with Sri Lanka's coastal environment, particularly along the West and South coasts.",
    specializations: ["Coastal Architecture", "Passive Design", "Commercial Buildings", "Residential Villas"],
    experience: [
      { company: "Gunasekara Architects", role: "Principal Architect", type: "Full-time", period: "Jul 2015 – Present", description: "Leads architectural design for coastal villas and commercial developments across the Western Province." },
      { company: "Arcades Design Studio", role: "Project Architect", type: "Full-time", period: "Jan 2009 – Jun 2015", description: "Delivered residential and hospitality projects across Negombo, Colombo, and Beruwala." },
    ],
    education: [{ school: "University of Moratuwa", dept: "Bachelor of Science in Architecture", period: "2003 – 2008" }],
    reviews: [
      { name: "Ishan de Silva", rating: 5, text: "Our beach house is everything we asked for — bright, airy, and built to last. Nishantha was a pleasure to work with." },
      { name: "Ruwan Pathirana", rating: 5, text: "He thought of things we hadn't even considered. The passive ventilation design keeps the house cool without AC." },
    ],
    portfolio: [
      { url: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800&h=600&fit=crop", caption: "Beach House, Negombo", category: "Residential" },
      { url: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop", caption: "Coastal Villa, Beruwala", category: "Residential" },
      { url: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=600&fit=crop", caption: "Commercial Building, Negombo", category: "Commercial" },
      { url: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&h=600&fit=crop", caption: "Passive Design Home, Colombo", category: "Residential" },
    ],
  },
  {
    id: 6, name: "Thamali Kumarasinghe", role: "Urban Designer", category: "Urban Design",
    rating: 4.6, reviewCount: 18,
    company: "UrbanForms Lanka",
    location: "Colombo 02, Sri Lanka",
    available: "17th Feb",
    hours: "9AM – 5PM",
    about: "Thamali is an urban designer focused on sustainable city planning and community-centred development in Sri Lanka. She has contributed to several urban regeneration projects in Colombo and works closely with municipal authorities on public space design.",
    specializations: ["Urban Regeneration", "Public Space Design", "Mixed-Use Development", "Community Planning"],
    experience: [
      { company: "UrbanForms Lanka", role: "Co-founder & Director", type: "Full-time", period: "Sep 2018 – Present", description: "Leads urban design initiatives in Colombo and secondary cities, focusing on walkability and green infrastructure." },
      { company: "Urban Development Authority (UDA)", role: "Urban Planner", type: "Full-time", period: "Jun 2013 – Aug 2018", description: "Contributed to master planning for the Colombo Port City and riverfront development projects." },
    ],
    education: [{ school: "University of Moratuwa", dept: "Town & Country Planning", period: "2008 – 2013" }],
    reviews: [
      { name: "Aruna Dissanayake", rating: 5, text: "Thamali's approach to community consultation made our neighbourhood project feel inclusive and well-planned." },
      { name: "Madhavi Samarasinghe", rating: 4, text: "Excellent strategic thinker with a great grasp of Colombo's unique planning challenges." },
    ],
    portfolio: [
      { url: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&h=600&fit=crop", caption: "Colombo Waterfront Masterplan", category: "Urban" },
      { url: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800&h=600&fit=crop", caption: "Public Square, Colombo 02", category: "Public Space" },
      { url: "https://images.unsplash.com/photo-1448630360428-65456885c650?w=800&h=600&fit=crop", caption: "Mixed-Use Development, Pettah", category: "Commercial" },
      { url: "https://images.unsplash.com/photo-1494522855154-9297ac14b55f?w=800&h=600&fit=crop", caption: "Green Corridor, Colombo", category: "Urban" },
    ],
  },
  {
    id: 7, name: "Pradeep Liyanage", role: "Structural Engineer", category: "Structural Engineering",
    rating: 4.3, reviewCount: 12,
    company: "Liyanage Structural Consultants",
    location: "Kandy, Sri Lanka",
    available: "18th Feb",
    hours: "8AM – 4PM",
    about: "Pradeep is a structural engineer with expertise in hillside construction and earthquake-resistant design for Sri Lanka's central highlands. He has consulted on residential, commercial, and infrastructure projects across the Kandy and Nuwara Eliya districts.",
    specializations: ["Hillside Construction", "Structural Assessments", "Residential Engineering", "Renovation Structural Work"],
    experience: [
      { company: "Liyanage Structural Consultants", role: "Principal Engineer", type: "Full-time", period: "Feb 2017 – Present", description: "Provides structural engineering consultancy for residential and commercial projects in the Central Province." },
      { company: "Sri Lanka Engineering Consultants", role: "Structural Engineer", type: "Full-time", period: "May 2011 – Jan 2017", description: "Worked on road, bridge, and building structural projects across the Central and Uva provinces." },
    ],
    education: [{ school: "University of Peradeniya", dept: "Civil Engineering", period: "2005 – 2010" }],
    reviews: [
      { name: "Nalaka Seneviratne", rating: 5, text: "Pradeep's hillside expertise gave us so much confidence during our build. Everything was handled precisely." },
      { name: "Chathuri Rathnayake", rating: 4, text: "Very thorough structural assessment. Found issues early that saved us a lot of money." },
    ],
    portfolio: [
      { url: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&h=600&fit=crop", caption: "Hillside Residence, Kandy", category: "Residential" },
      { url: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800&h=600&fit=crop", caption: "Bridge Assessment, Nuwara Eliya", category: "Infrastructure" },
      { url: "https://images.unsplash.com/photo-1587293852726-70cdb56c2866?w=800&h=600&fit=crop", caption: "Commercial Build, Kandy", category: "Commercial" },
    ],
  },
  {
    id: 8, name: "Sampath Jayawardena", role: "Contractor", category: "Construction",
    rating: 4.6, reviewCount: 22,
    company: "Jayawardena Builders",
    location: "Colombo 10, Sri Lanka",
    available: "19th Feb",
    hours: "7AM – 5PM",
    about: "Sampath runs one of Colombo's most trusted construction firms, specialising in residential and commercial builds from foundation to handover. With over 18 years in the field, he is known for delivering on schedule and managing complex multi-trade projects with precision.",
    specializations: ["Residential Construction", "Commercial Builds", "Renovation & Extension", "Project Management"],
    experience: [
      { company: "Jayawardena Builders", role: "Managing Director", type: "Full-time", period: "Mar 2014 – Present", description: "Oversees end-to-end construction of residential and commercial projects across the Western Province, managing teams of 50+ tradespeople." },
      { company: "SL Build Co.", role: "Senior Project Manager", type: "Full-time", period: "Jan 2006 – Feb 2014", description: "Managed construction of hotel and condominium projects in Colombo and Negombo." },
    ],
    education: [{ school: "University of Moratuwa", dept: "Civil Engineering", period: "2000 – 2005" }],
    reviews: [
      { name: "Vikram Perera", rating: 5, text: "Sampath delivered our three-storey home on time and within budget. His team was professional throughout." },
      { name: "Renuka Silva", rating: 4, text: "Great project management. He kept us informed at every stage and solved problems quickly." },
    ],
    portfolio: [
      { url: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=800&h=600&fit=crop", caption: "Three-Storey Residence, Colombo", category: "Residential" },
      { url: "https://images.unsplash.com/photo-1590274853856-f22d5ee3d228?w=800&h=600&fit=crop", caption: "Commercial Fit-out, Colombo 03", category: "Commercial" },
      { url: "https://images.unsplash.com/photo-1565008447742-97f6f38c985c?w=800&h=600&fit=crop", caption: "Hotel Construction, Negombo", category: "Hospitality" },
      { url: "https://images.unsplash.com/photo-1558618047-f4e60e042acf?w=800&h=600&fit=crop", caption: "Home Extension, Nugegoda", category: "Residential" },
    ],
  },
  {
    id: 9, name: "Ishara Bandara", role: "Quantity Surveyor", category: "Quantity Surveying",
    rating: 4.5, reviewCount: 14,
    company: "Bandara Cost Consultants",
    location: "Colombo 05, Sri Lanka",
    available: "20th Feb",
    hours: "9AM – 6PM",
    about: "Ishara is a chartered quantity surveyor with deep expertise in construction cost management across residential, commercial, and hospitality projects in Sri Lanka. She helps clients understand true project costs before work begins, avoiding expensive surprises during construction.",
    specializations: ["Cost Estimation", "Bill of Quantities", "Contract Administration", "Value Engineering"],
    experience: [
      { company: "Bandara Cost Consultants", role: "Principal Quantity Surveyor", type: "Full-time", period: "Jun 2019 – Present", description: "Provides independent cost consultancy to developers, architects, and private clients across Sri Lanka." },
      { company: "Davis Langdon Lanka", role: "Senior QS", type: "Full-time", period: "Sep 2013 – May 2019", description: "Delivered cost planning and contract administration for large commercial and mixed-use projects in Colombo." },
    ],
    education: [{ school: "University of Moratuwa", dept: "Quantity Surveying", period: "2008 – 2013" }],
    reviews: [
      { name: "Asanka Fernando", rating: 5, text: "Ishara's cost plan was spot-on. She caught overpriced contractor quotes we never would have noticed ourselves." },
      { name: "Nadeeka Gunawardena", rating: 4, text: "Very thorough and professional. Her BOQ saved us significant money during tender negotiations." },
    ],
    portfolio: [
      { url: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=600&fit=crop", caption: "Cost Plan — Mixed-Use, Colombo", category: "Commercial" },
      { url: "https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?w=800&h=600&fit=crop", caption: "BOQ — Luxury Residences", category: "Residential" },
      { url: "https://images.unsplash.com/photo-1556761175-4b46a572b786?w=800&h=600&fit=crop", caption: "Tender Negotiation — Hotel Project", category: "Hospitality" },
    ],
  },
]

export type Architect = typeof architects[0]
