export const architects = [
  {
    id: 1, name: "Roshan Perera", role: "Architect", rating: 4.9, reviewCount: 34,
    photo: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=120&auto=format&fit=crop&q=80",
    company: "Perera & Associates",
    location: "Colombo 03, Sri Lanka",
    available: "10th Feb",
    hours: "9AM – 6PM",
    about: "Roshan is a leading architect based in Colombo with over 12 years of experience in residential, commercial, and hospitality projects across Sri Lanka. Inspired by Geoffrey Bawa's tropical modernism, he creates spaces that breathe with the island's climate and landscape.",
    specializations: ["Tropical Modernism", "Residential Design", "Hospitality & Resorts", "Sustainable Construction"],
    experience: [
      { company: "Perera & Associates", role: "Principal Architect", type: "Full-time", period: "Jan 2016 – Present", description: "Leads a Colombo-based practice delivering award-winning residential and resort projects across Sri Lanka." },
      { company: "Bawa Architecture Studio", role: "Senior Architect", type: "Full-time", period: "Mar 2011 – Dec 2015", description: "Worked on high-profile hospitality and private residence projects in Galle and Bentota." },
    ],
    education: [{ school: "University of Moratuwa", dept: "Bachelor of Science in Architecture", period: "2004 – 2009" }],
    reviews: [
      { name: "Chaminda Jayawardena", rating: 5, text: "Roshan understood exactly what we wanted — a home that feels open, breezy, and rooted in Sri Lanka. Exceptional work." },
      { name: "Nilufar Hameed", rating: 5, text: "His knowledge of tropical design is unmatched. Our villa in Weligama is everything we dreamed of." },
    ],
  },
  {
    id: 2, name: "Dilani Wijesinghe", role: "Interior Designer", rating: 4.7, reviewCount: 21,
    photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80",
    company: "Studio Dilani",
    location: "Colombo 07, Sri Lanka",
    available: "12th Feb",
    hours: "10AM – 7PM",
    about: "Dilani brings a sophisticated blend of Sri Lankan artisan tradition and contemporary design to every interior. Her work celebrates local craftsmanship — lacquerwork, brass, handloom textiles — woven into modern, liveable spaces.",
    specializations: ["Luxury Residential", "Boutique Hospitality", "Local Craft Integration", "Space Planning"],
    experience: [
      { company: "Studio Dilani", role: "Creative Director", type: "Full-time", period: "Aug 2019 – Present", description: "Runs a boutique interior design studio in Colombo 7, known for blending contemporary aesthetics with Sri Lankan craft." },
      { company: "Hiran Cooray Design Group", role: "Senior Designer", type: "Full-time", period: "Feb 2014 – Jul 2019", description: "Led interior design for several boutique hotels and private residences across Colombo and the South Coast." },
    ],
    education: [{ school: "SLIIT", dept: "Interior Design", period: "2009 – 2013" }],
    reviews: [
      { name: "Sanjaya Mendis", rating: 5, text: "Dilani transformed our apartment in Colombo 7 into something truly special. She understood our taste immediately." },
      { name: "Preethi Fernando", rating: 4, text: "Beautiful work. She sourced local materials we never would have found ourselves. Very pleased with the result." },
    ],
  },
  {
    id: 3, name: "Kavinda Rajapaksa", role: "Landscape Architect", rating: 4.5, reviewCount: 16,
    photo: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80",
    company: "Greenlane Lanka",
    location: "Kandy, Sri Lanka",
    available: "14th Feb",
    hours: "8AM – 5PM",
    about: "Kavinda specialises in tropical landscape architecture, creating gardens and outdoor environments that thrive in Sri Lanka's climate. His projects range from private tea estate gardens to resort grounds and urban green spaces.",
    specializations: ["Tropical Garden Design", "Resort Landscaping", "Water Features", "Sustainable Planting"],
    experience: [
      { company: "Greenlane Lanka", role: "Principal Landscape Architect", type: "Full-time", period: "Apr 2018 – Present", description: "Delivers residential and resort landscape projects across the Hill Country and South Coast." },
      { company: "Scape Studio", role: "Landscape Architect", type: "Full-time", period: "Jun 2012 – Mar 2018", description: "Contributed to large-scale resort and hotel grounds projects in Galle, Bentota, and Sigiriya." },
    ],
    education: [{ school: "University of Peradeniya", dept: "Agriculture & Landscape Design", period: "2007 – 2011" }],
    reviews: [
      { name: "Tharanga Wickramasinghe", rating: 5, text: "Our tea estate garden is now the highlight of every guest visit. Kavinda has an extraordinary eye for tropical planting." },
      { name: "Suresh Bandara", rating: 4, text: "Very professional and full of great ideas. The resort grounds look stunning." },
    ],
  },
  {
    id: 4, name: "Amali Senanayake", role: "Interior Designer", rating: 4.4, reviewCount: 13,
    photo: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&auto=format&fit=crop&q=80",
    company: "Amali Design Co.",
    location: "Galle, Sri Lanka",
    available: "15th Feb",
    hours: "9AM – 5PM",
    about: "Amali is based in Galle and specialises in heritage renovation and colonial-style interiors. She has a deep appreciation for the Dutch colonial architecture of the Galle Fort area and brings that sensitivity to residential and boutique hotel projects.",
    specializations: ["Heritage Renovation", "Colonial Interiors", "Boutique Hotels", "Material Sourcing"],
    experience: [
      { company: "Amali Design Co.", role: "Founder & Lead Designer", type: "Full-time", period: "Mar 2020 – Present", description: "Runs an independent studio focused on heritage home renovations and boutique hotel interiors in the South." },
      { company: "Galle Heritage Trust", role: "Design Consultant", type: "Contract", period: "Jan 2016 – Feb 2020", description: "Provided interior design consultancy for heritage property restorations within the Galle Fort UNESCO zone." },
    ],
    education: [{ school: "University of Moratuwa", dept: "Architecture", period: "2010 – 2015" }],
    reviews: [
      { name: "Hannah Webb", rating: 5, text: "Amali restored our Galle Fort villa with incredible care and taste. Every detail is perfect." },
      { name: "Kasun Ranatunga", rating: 4, text: "Deeply knowledgeable about heritage properties. Our home feels authentic and beautiful." },
    ],
  },
  {
    id: 5, name: "Nishantha Gunasekara", role: "Architect", rating: 4.8, reviewCount: 27,
    photo: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=80&auto=format&fit=crop&q=80",
    company: "Gunasekara Architects",
    location: "Negombo, Sri Lanka",
    available: "16th Feb",
    hours: "9AM – 6PM",
    about: "Nishantha brings 15 years of experience in coastal residential and commercial design. He specialises in buildings that maximise natural ventilation and integrate seamlessly with Sri Lanka's coastal environment, particularly along the West and South coasts.",
    specializations: ["Coastal Architecture", "Passive Design", "Commercial Buildings", "Residential Villas"],
    experience: [
      { company: "Gunasekara Architects", role: "Principal Architect", type: "Full-time", period: "Jul 2015 – Present", description: "Leads architectural design for coastal villas and commercial developments across the Western Province." },
      { company: "Arcades Design Studio", role: "Project Architect", type: "Full-time", period: "Jan 2009 – Jun 2015", description: "Delivered residential and hospitality projects across Negombo, Colombo, and Beruwala." },
    ],
    education: [{ school: "University of Moratuwa", dept: "Bachelor of Science in Architecture", period: "2003 – 2008" }],
    reviews: [
      { name: "Ishan de Silva", rating: 5, text: "Our beach house is everything we asked for — bright, airy, and built to last. Nishantha was a pleasure to work with." },
      { name: "Ruwan Pathirana", rating: 5, text: "He thought of things we hadn't even considered. The passive ventilation design keeps the house cool without AC." },
    ],
  },
  {
    id: 6, name: "Thamali Kumarasinghe", role: "Urban Designer", rating: 4.6, reviewCount: 18,
    photo: "",
    company: "UrbanForms Lanka",
    location: "Colombo 02, Sri Lanka",
    available: "17th Feb",
    hours: "9AM – 5PM",
    about: "Thamali is an urban designer focused on sustainable city planning and community-centred development in Sri Lanka. She has contributed to several urban regeneration projects in Colombo and works closely with municipal authorities on public space design.",
    specializations: ["Urban Regeneration", "Public Space Design", "Mixed-Use Development", "Community Planning"],
    experience: [
      { company: "UrbanForms Lanka", role: "Co-founder & Director", type: "Full-time", period: "Sep 2018 – Present", description: "Leads urban design initiatives in Colombo and secondary cities, focusing on walkability and green infrastructure." },
      { company: "Urban Development Authority (UDA)", role: "Urban Planner", type: "Full-time", period: "Jun 2013 – Aug 2018", description: "Contributed to master planning for the Colombo Port City and riverfront development projects." },
    ],
    education: [{ school: "University of Moratuwa", dept: "Town & Country Planning", period: "2008 – 2013" }],
    reviews: [
      { name: "Aruna Dissanayake", rating: 5, text: "Thamali's approach to community consultation made our neighbourhood project feel inclusive and well-planned." },
      { name: "Madhavi Samarasinghe", rating: 4, text: "Excellent strategic thinker with a great grasp of Colombo's unique planning challenges." },
    ],
  },
  {
    id: 7, name: "Pradeep Liyanage", role: "Structural Engineer", rating: 4.3, reviewCount: 12,
    photo: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=80&auto=format&fit=crop&q=80",
    company: "Liyanage Structural Consultants",
    location: "Kandy, Sri Lanka",
    available: "18th Feb",
    hours: "8AM – 4PM",
    about: "Pradeep is a structural engineer with expertise in hillside construction and earthquake-resistant design for Sri Lanka's central highlands. He has consulted on residential, commercial, and infrastructure projects across the Kandy and Nuwara Eliya districts.",
    specializations: ["Hillside Construction", "Structural Assessments", "Residential Engineering", "Renovation Structural Work"],
    experience: [
      { company: "Liyanage Structural Consultants", role: "Principal Engineer", type: "Full-time", period: "Feb 2017 – Present", description: "Provides structural engineering consultancy for residential and commercial projects in the Central Province." },
      { company: "Sri Lanka Engineering Consultants", role: "Structural Engineer", type: "Full-time", period: "May 2011 – Jan 2017", description: "Worked on road, bridge, and building structural projects across the Central and Uva provinces." },
    ],
    education: [{ school: "University of Peradeniya", dept: "Civil Engineering", period: "2005 – 2010" }],
    reviews: [
      { name: "Nalaka Seneviratne", rating: 5, text: "Pradeep's hillside expertise gave us so much confidence during our build. Everything was handled precisely." },
      { name: "Chathuri Rathnayake", rating: 4, text: "Very thorough structural assessment. Found issues early that saved us a lot of money." },
    ],
  },
]

export type Architect = typeof architects[0]
